name: CI Node

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}

    # ép toàn bộ step chạy bash (cả Ubuntu & Windows)
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Lint nghiêm CHỈ khi mở PR
      - name: Lint (strict on PR)
        if: ${{ github.event_name == 'pull_request'
                && !contains(github.event.pull_request.title, '[skip-lint]')
                && !contains(github.event.pull_request.body,  '[skip-lint]') }}
        run: |
          if npm run -s | grep -q "^  lint:ci"; then
            npm run lint:ci
          elif npm run -s | grep -q "^  lint"; then
            npx eslint . --max-warnings=0
          else
            echo "No lint script"
          fi

      # Test luôn chạy nếu có script test
      - name: Test (always)
        run: |
          if npm run -s | grep -q "^  test"; then
            npm test --silent
          else
            echo "No test script"
          fi
