# .github/workflows/ci-node.yml
name: CI Node

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
        shell: bash

      # Lint nghiêm KHỎI chạy khi push, CHỈ chạy khi là pull_request
      - name: Lint (strict on PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint:ci

      # Khi push: chỉ test/smoke cho đỡ đỏ
      - name: Test (always)
        run: |
          if npm run | grep -q "test"; then npm test --silent; else echo "No test script"; fi
        shell: bash
